export interface PhotoUploader {
  _id: string;
  name: string;
  email: string;
}

export interface Photo {
  _id: string;
  event: string;
  uploadedBy: PhotoUploader | string;
  originalName: string;
  storageKey: string;
  size?: number;
  mimeType?: string;
  isSelected: boolean;
  /** Temporary signed read URL generated by the backend */
  url: string;
  createdAt: string;
  updatedAt: string;
}

export interface SignedUrlResponse {
  uploadUrl: string;
  storageKey: string;
}

export interface GetSignedUrlInput {
  eventId: string;
  originalName: string;
  contentType: string;
}

export interface SaveMetadataInput {
  eventId: string;
  storageKey: string;
  originalName: string;
  size?: number;
  mimeType?: string;
}

// ─── Upload Queue ───────────────────────────────────────────────────────────

export type UploadStatus = "pending" | "uploading" | "complete" | "failed";

export interface UploadItem {
  /** Client-side unique ID */
  id: string;
  file: File;
  status: UploadStatus;
  /** 0–100 */
  progress: number;
  error?: string;
  /** Revocable object URL for image preview thumbnail */
  thumbnail?: string;
}
